apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  # userarn 需要修改为自己的
  mapUsers: |
    - userarn: arn:aws:iam::111222333:user/github-ci
      username: github-ci
      groups:
        - system:masters