test-demo:
  URI: "amqp://guest:guest@localhost:5672/"
  AutoDeclare: true
  Timeout: 5s
  Exchange:
    Name: local-test-exchange
    Kind: direct
    Durable: true
    AutoDelete: false
    Internal: false
    NoWait: false
    Args: {}
  Queue:
    name: local-test-queue
    durable: true
    AutoDelete: false
    Exclusive: false
    NoWait: false
    Args: {}
  Bind:
    RoutingKey: local-test-routing-key
    NoWait: false
    Args: {}

test-multi:
  URI: "amqp://guest:guest@localhost:5672/"
  AutoDeclare: true
  Timeout: 5s
  Exchange:
    Name: local-test2-exchange
    Kind: direct
    Durable: true
    AutoDelete: false
    Internal: false
    NoWait: false
    Args: {}
  Queue:
    name: local-test2-queue
    durable: true
    AutoDelete: false
    Exclusive: false
    NoWait: false
    Args: {}
  Bind:
    RoutingKey: local-test2-routing-key
    NoWait: false
    Args: {}